### PR TITLE
Simplify closures

### PR DESCRIPTION
**Pull request by eldruin**
Good idea @ryankurte! Here some small simplifications.

I also have a question: Why do you bind the error types to the driver object?

### CODE REVIEW

**Comment by NOP0** [comment]
@eldruin That's really nice, but why are we allowed to write map_err like that, given the signature for map_err under?  Stumbled on this by random, hope you don't mind a stupid question :smile: 
```
pub fn map_err<F, O>(self, op: O) -> Result<T, F> where
    O: FnOnce(E) -> F, 
```

**Comment by ryankurte** [comment]
> I also have a question: Why do you bind the error types to the driver object?

As opposed to per-function? It's so that when you instantiate / store a driver object the error types come with it.

> ... why are we allowed to write map_err like that ...

It's a bit niche, but, afaik an enum constructor can also be used as a function, so, for `enum Test { A(u16) }`, there is a constructor `Test::A(u16)`. You can see this from the error you get from trying to invoke `let a = Test::A;`. There's a wee bit of documentation on this [here](https://doc.rust-lang.org/1.30.0/book/first-edition/enums.html#constructors-as-functions)

**Comment by eldruin** [comment]
@ryankurte not per-function but per-impl-block. I usually do this:
```rust
pub struct Veml6030<I2C> {
    i2c: I2C,
}

impl<I2C, E> Veml6030<I2C>
where
    I2C: i2c::Write<Error = E>,
{
    pub fn enable(&mut self) -> Result<(), Error<E>> {
        // ...
    }
}
```
I was wondering what the reason is to bind the error types like [this](https://github.com/ryankurte/rust-embedded-driver/blob/d15c1b4d350146518c3670d3372109c7a0ad8ad7/src/lib.rs#L64)

**Comment by NOP0** [comment]
@ryankurte Thanks for the explanation, I appreciate it 👍

**Pull request merged**
